import 'package:flutter/material.dart';
import '../theme/theme.dart';
import '../widgets/history_list_item.dart';
import '../widgets/progress_card.dart';
import '../models/models.dart';

class HistoryScreen extends StatefulWidget {
  const HistoryScreen({super.key});

  @override
  State<HistoryScreen> createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> {
  String _selectedFilter = 'All Problems';
  final List<String> _filters = ['All Problems', 'Calculus', 'Linear Algebra', 'Algebra'];

  @override
  Widget build(BuildContext context) {
    // Mock history items
    final todayItems = [
      HistoryItem(
        id: '1',
        problem: Problem(
          id: 'p1',
          title: 'Integration by Parts',
          rawEquation: '∫ x cos(x) dx',
          subject: 'Calculus II',
          topic: 'Integration Techniques',
          level: DifficultyLevel.advanced,
          status: ProblemStatus.solved,
          createdAt: DateTime.now(),
          isVerified: true,
        ),
        solution: Solution(
          id: 's1',
          problemId: 'p1',
          finalAnswer: 'x sin(x) + cos(x) + C',
          steps: [],
          method: 'Integration by Parts',
          solvedAt: DateTime.now(),
        ),
        timestamp: DateTime.now(),
      ),
      HistoryItem(
        id: '2',
        problem: Problem(
          id: 'p2',
          title: 'Matrix Determinant 3x3',
          rawEquation: 'det(A) = -142',
          subject: 'Linear Algebra',
          topic: 'Matrix Operations',
          level: DifficultyLevel.intermediate,
          status: ProblemStatus.solved,
          createdAt: DateTime.now(),
          isVerified: true,
        ),
        solution: Solution(
          id: 's2',
          problemId: 'p2',
          finalAnswer: 'det(A) = -142',
          steps: [],
          method: 'Cofactor Expansion',
          solvedAt: DateTime.now(),
        ),
        timestamp: DateTime.now(),
      ),
    ];

    final yesterdayItems = [
      HistoryItem(
        id: '3',
        problem: Problem(
          id: 'p3',
          title: 'Solids of Revolution',
          rawEquation: 'Find the volume of the solid generated by revolving the region...',
          subject: 'Geometry/Calculus',
          topic: 'Volume Calculations',
          level: DifficultyLevel.graduate,
          status: ProblemStatus.archived,
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          isVerified: true,
        ),
        solution: Solution(
          id: 's3',
          problemId: 'p3',
          finalAnswer: 'V = 8π/3 units³',
          steps: [],
          method: 'Disk Method',
          solvedAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
      ),
    ];

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.menu),
          onPressed: () {},
        ),
        title: const Text('Academic Atelier'),
        actions: [
          CircleAvatar(
            radius: 16,
            backgroundColor: Colors.grey[300],
            child: const Icon(Icons.person, size: 18),
          ),
          const SizedBox(width: 16),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 16),
            
            // Header section
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'YOUR COLLECTION',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: AppColors.textSecondary,
                      letterSpacing: 0.5,
                    ),
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'History',
                    style: TextStyle(
                      fontSize: 32,
                      fontWeight: FontWeight.bold,
                      color: AppColors.textPrimary,
                    ),
                  ),
                ],
              ),
            ),
            
            const SizedBox(height: 16),
            
            // Search bar
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: TextField(
                decoration: InputDecoration(
                  hintText: 'Search equations or topics...',
                  hintStyle: const TextStyle(color: AppColors.textSecondary),
                  prefixIcon: const Icon(Icons.search, color: AppColors.textSecondary),
                  filled: true,
                  fillColor: AppColors.surface,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide.none,
                  ),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                ),
              ),
            ),
            
            const SizedBox(height: 20),
            
            // Filter chips
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: _filters.map((filter) {
                    final isSelected = filter == _selectedFilter;
                    return Padding(
                      padding: const EdgeInsets.only(right: 8),
                      child: ChoiceChip(
                        label: Text(filter),
                        selected: isSelected,
                        onSelected: (selected) {
                          setState(() {
                            _selectedFilter = filter;
                          });
                        },
                        backgroundColor: AppColors.surface,
                        selectedColor: AppColors.primaryDark,
                        labelStyle: TextStyle(
                          color: isSelected ? Colors.white : AppColors.textPrimary,
                          fontWeight: FontWeight.w500,
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                      ),
                    );
                  }).toList(),
                ),
              ),
            ),
            
            const SizedBox(height: 24),
            
            // Today's section
            const Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Text(
                'TODAY',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: AppColors.textSecondary,
                  letterSpacing: 0.5,
                ),
              ),
            ),
            
            const SizedBox(height: 12),
            
            // Today's items
            ...todayItems.map((item) => HistoryListItem(
              title: item.problem.title,
              topic: item.problem.topic,
              level: item.problem.levelLabel,
              finalResult: item.solution?.finalAnswer ?? 'No solution',
              status: item.problem.statusLabel,
              timestamp: item.timestamp,
              isFavorite: item.isFavorite,
              onTap: () {},
              onShare: () {},
              onFavorite: () {},
            )),
            
            const SizedBox(height: 24),
            
            // Yesterday's section
            const Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Text(
                'YESTERDAY',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: AppColors.textSecondary,
                  letterSpacing: 0.5,
                ),
              ),
            ),
            
            const SizedBox(height: 12),
            
            // Yesterday's items
            ...yesterdayItems.map((item) => HistoryListItem(
              title: item.problem.title,
              topic: item.problem.topic,
              level: item.problem.levelLabel,
              finalResult: item.solution?.finalAnswer ?? 'No solution',
              status: item.problem.statusLabel,
              timestamp: item.timestamp,
              isFavorite: item.isFavorite,
              onTap: () {},
              onShare: () {},
              onFavorite: () {},
            )),
            
            const SizedBox(height: 24),
            
            // Progress card
            const ProgressCard(
              totalSolved: 89,
              dayStreak: 12,
              formulasMastered: 14,
            ),
            
            const SizedBox(height: 100),
          ],
        ),
      ),
    );
  }
}
